# arch/arm/plat-canopus/Makefile
#
# Copyright 2010 Unidata
#
# Licensed under GPLv2

obj-y				:=
obj-m				:=
obj-n				:=
obj-				:=

# Core files
obj-$(CONFIG_MACH_CANOPUS)	+= param.o
obj-$(CONFIG_MACH_CANOPUS)	+= nand_cp.o
obj-$(CONFIG_MACH_CANOPUS)	+= crc32.o
