
# obj-$(CONFIG_VIDEO_VM_VC0528)        += vc0528_driver.o
# obj-$(CONFIG_VIDEO_VM_VC0528)        += camera_if.o
obj-$(CONFIG_VC0528)         += VIM_5X_API.o \
								VIM_DISP_Driver.o VIM_DRIVERIC_Info.o \
								VIM_HIF_Driver.o VIM_HIGH_API.o VIM_IPP_Driver.o \
								VIM_JPEG_Driver.o VIM_LCDIF_Driver.o \
								VIM_MARB_Driver.o VIM_MID_API.o \
								VIM_SENSOR_Info.o \
								VIM_SIF_Driver.o

obj-$(CONFIG_VC0528)         += VIM_USER_Info.o


